//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bar
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;

    using System.ComponentModel.DataAnnotations;
    public partial class Customer
    {
        [Key]

        public int OrderID { get; set; }
        [Required(ErrorMessage = "Please Input Customer Order Name", AllowEmptyStrings = false)]
        public string OrderName { get; set; }
        public string Status { get; set; }
    
       
        public virtual ICollection<Order> Orders { get; set; }
    }
}
